[package]
name = "controller"
version = "0.1.0"
edition = "2021"

[dependencies]
account_sdk = { git = "https://github.com/cartridge-gg/controller", package = "account_sdk" }
starknet = "0.12.0"
tokio = { version = "1.42.0", features = ["full"] }
